image:
  - Visual Studio 2017

shallow_clone: true

cache: C:\Tools\vcpkg\installed\

install:
  - vcpkg install boost-test:x64-windows
  - vcpkg install boost-ublas:x64-windows
  - vcpkg install glm:x64-windows

build_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake -G "Visual Studio 15 2017 Win64" ..
  - cmake --build . --config Debug

test_script:
  - ctest -C Debug --output-on-failure
